### ISSUE TITLE
Node.js 16 deprecation warning.  Request update to Node.js 20.

### ISSUE THREAD

**Issue by JamesParrott** [Caphyon/advinst-github-action#12]
This is a great Action!  Thanks very much Team Caphyon for providing it.

I just wanted to bring the deprecation warning below to your attention (Node 16 needs to be updated to Node 20).  

I'll take a look later, it should be a simple fix.

![image](https://github.com/Caphyon/advinst-github-action/assets/80779630/2fb51b3a-16a4-4248-9ad8-9b989e4f46e1)

```
>Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: 
caphyon/advinst-github-action@v1.1. For more information see: 
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20
```

**Comment by burcadoruciprian** [comment]
Fived in our latest release (v2.0)
