### ISSUE TITLE
Error while running the action on Linux

### ISSUE THREAD

**Issue by pgolinski** [Caphyon/advinst-github-action#2]
I've tried to run this action on linux, but it didn't pass even preparation step:

![image](https://user-images.githubusercontent.com/5859367/201680309-ca6e4985-dad0-4aba-bec3-b851473d0a2a.png)

That is because there are backslashes in the paths:
https://github.com/Caphyon/advinst-github-action/blob/784f9ea25045e7458e8d08391703e7c5f17c5be4/action.yml#L33

The readme doesn't mention required operating system and I wonder if it is the only reason I cannot run it on Linux?

**Comment by burcadoruciprian** [comment]
Hi,
@pgolinski  this actions requires a windows client

**Comment by pgolinski** [comment]
Ok. Thank you.
