### ISSUE TITLE
advancedinstaller.com' failed with exit code 3221226356

### ISSUE THREAD

**Issue by fcollasso** [Caphyon/advinst-github-action#4]
Hello, weeks ago my action was working fine using the SetAzureKeyVaultSecret command, but now I'm having this error after executing the command. I tested my key vault directly through the Advanced Installer and it is working correctly. Do you know this error? Thank you very much.

**Comment by monrapps** [comment]
u3221226356 / -1073740940 errors are related to the KB5022282 windows security update, that is currently installed on windows-2019 and windows-latest runners. Fixed on Advanced Installer 20.2.1. unfortunately we had to buy another year of maintenance to get that update.
