### ISSUE TITLE
Using a License Key or License Server does not work

### ISSUE THREAD

**Issue by michaelchambaud-eaton** [Caphyon/advinst-github-action#7]
We have Advanced Installer Enterprise installed on a VM, that VM is a agent for a Bamboo instance we currently use but we're looking to move to GHE and Github Actions. 

I'm trying to use this action but I get the following error when I enter our `license key` or `<host>:<port>` into the `advinst-license` field.

![image](https://github.com/Caphyon/advinst-github-action/assets/144717859/31f1eae0-c0f5-443a-a689-1c7c97460667)

I had a look through the code and it does not look like I can use the `license server`.

**Comment by burcadoruciprian** [comment]
The action action was designed to work with newer version of Advanced Installer in order to benefit from the latest features like PowerShell integration. This error seems to indicate you are using an older version

**Comment by michaelchambaud-eaton** [comment]
I see, I will try and see if our AIP works with new versions.

**Comment by burcadoruciprian** [comment]
You need a valid license to use github actions and floating licenses are not supported. Please contact the advanced installer support and they will help you.

**Comment by michaelchambaud-eaton** [comment]
I did, they said to use the trial. Perhaps documentation could be updated with more information in the license section,

It's too bad, it should be easy for developers to tests things before the company shells outs thousands of dollars on software.

**Comment by burcadoruciprian** [comment]
Sorry about that. Unfortunately there are certain limitations on the azure client vm's which prevent us to fully deploy the AI tool with trial. There is however a workaround, if you care to try it. You can add a [self-hostet](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/windows-agent?view=azure-devops) agent to azure. You can then manually install a trial copy of advinst on that machine and perform your tests.
