### ISSUE TITLE
How to cache advinst tool?

### ISSUE THREAD

**Issue by zhaoqiu-china** [Caphyon/advinst-github-action#8]
Hi, thanks to your work.
Are there some arguments for caching advinst tool?
I find some code as follow:
```js
async getPath(): Promise<string> {
    //Check cache first
    core.info(`Checking cache for advinst tool with version: ${this.version}`);
    let toolRoot = toolCache.find(
      AdvinstTool.advinstCacheToolName,
      this.version,
      AdvinstTool.advinstCacheToolArch
    );

}

```

**Comment by sgammon** [comment]
@zhaoqiu-china this is the "Tool Cache" which you can read about in the [Actions Toolkit](https://github.com/actions/toolkit), it will prevent Advanced Installer from re-installing on the same machine if it has already been installed

it isn't a build cache, or a dependency cache, it's for the Advanced Installer binary itself

there are other ways to build cache though if you are interested let me know

**Comment by zhaoqiu-china** [comment]
@sgammon Thanks to your reply. I want to know whether some options, like `cache = ture`, exist in your action.
for example, for the `install-qt` action, I will set cache to true to prevent qt environment.

![image](https://github.com/Caphyon/advinst-github-action/assets/51221150/43cf6a9d-297d-4e18-ba80-347430be15d9)

**Comment by sgammon** [comment]
Sorry, @zhaoqiu-china, this is not my action, I am just trying to help :)

Advanced Installer does limited build caching. It will put a folder next to your project, if I recall correctly, called `YourProject.cache`. The feature is documented [here](https://www.advancedinstaller.com/user-guide/project-cache-tab.html#:~:text=project's%20caching%20options.-,Caching,stored%20archive%20will%20be%20reused.)

You would use the [`actions/cache`](https://github.com/actions/cache) action, which is made by Github, and configure it with the path where the cache is written.

This way, the action will wait until a build occurs, upload your cache folder made by Advanced Installer, and then restore it for the next build run. Is that what you're after? Hope this helps.
