### ISSUE TITLE
Bug with action on non-Windows platforms

### ISSUE THREAD

**Issue by sgammon** [Caphyon/advinst-github-action#9]
Hello esteemed Advanced Installer action authors,

We are using this action to build an Advanced Installer project, but sometimes the underlying runner is Linux or macOS; in these cases, we disable the action with `if: <something that evaluates to false>`. All's well and good, except that the _Post action_ step runs unconditionally, and since it runs on Linux and/or macOS, it fails.

An otherwise valid and green build throws an error looking like this:
```
File not found: '/home/runner/work/_actions/caphyon/advinst-github-action/main/dist\post\index.js'
```

Inspecting the logs shows:
<img width="887" alt="Screenshot 2023-12-11 at 8 20 30 PM" src="https://github.com/Caphyon/advinst-github-action/assets/171897/c644c077-8713-4210-a26c-f1562c45afd5">

**Comment by sgammon** [comment]
Sorry, accidentally closed when I merged to `main` on my fork.

**Comment by sgammon** [comment]
@burcadoruciprian friendly ping?

**Comment by burcadoruciprian** [comment]
Hello @sgammon.  I will look into this and get back to you

**Comment by sgammon** [comment]
@burcadoruciprian sounds good! But just so you know we've posted a fix PR :)

**Comment by sgammon** [comment]
It works great on our fork after testing with Linux, macOS, and Windows of course.
